---

# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for onos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullPolicy: IfNotPresent
onosImage: 'onos-fabric-mwc:candidate'

nameOverride: ""
fullnameOverride: ""

namespace: default
serviceAccountName: default

services:
  openflowServiceType: NodePort
  ovsdbServiceType: NodePort
  sshServiceType: NodePort
  uiServiceType: NodePort
  clusterServiceType: ClusterIP
  fpcServiceType: ClusterIP
  vspgwuServiceType: ClusterIP
  ovsdb:
    port: 6640
    nodePort: 31640
  openflow:
    port: 6653
    nodePort: 31653
  ssh:
    port: 8101
    nodePort: 31101
  ui:
    port: 8181
    nodePort: 31181
  cluster:
    port: 9876
  fpc:
    port: 8070
  fpcTopology:
    port: 8181
  vspgwu:
    port: 20

onos_env: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

xos_service_label: ""
